-- MySQL Script generated by MySQL Workbench
-- qui 02 abr 2020 13:39:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema drone
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema drone
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `drone` ;
CREATE SCHEMA IF NOT EXISTS `drone` ;
USE `drone` ;

-- -----------------------------------------------------
-- Table `drone`.`juiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drone`.`juiz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`))
AUTO_INCREMENT = 1
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `drone`.`campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drone`.`campeonato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `juiz_id` INT NOT NULL,
  PRIMARY KEY (`id`, `juiz_id`),
  CONSTRAINT `fk_campeonato_juiz`
    FOREIGN KEY (`juiz_id`)
    REFERENCES `drone`.`juiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `drone`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drone`.`equipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `drone`.`resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `drone`.`resultados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `arco_1` TINYINT NULL,
  `arco_2` TINYINT NULL,
  `placa` TINYINT NULL,
  `golf` TINYINT NULL,
  `cronometro` INT NULL,
  `equipe_id` INT NOT NULL,
  `campeonato_id` INT NOT NULL,
  `campeonato_juiz_id` INT NOT NULL,
  PRIMARY KEY (`id`,`equipe_id`,`campeonato_id`),
  CONSTRAINT `fk_resultados_equipe`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `drone`.`equipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultados_campeonato`
    FOREIGN KEY (`campeonato_id`, `campeonato_juiz_id`)
    REFERENCES `drone`.`campeonato` (`id`, `juiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `drone`.`juiz`
-- -----------------------------------------------------
START TRANSACTION;
USE `drone`;
INSERT INTO `drone`.`juiz` (`username`, `email`, `password`) VALUES ('admin', 'admin@g.com', '123456');

COMMIT;


-- -----------------------------------------------------
-- Data for table `drone`.`campeonato`
-- -----------------------------------------------------
START TRANSACTION;
USE `drone`;
INSERT INTO `drone`.`campeonato` (`Nome`, `juiz_id`) VALUES ('unoesc', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `drone`.`equipe`
-- -----------------------------------------------------
START TRANSACTION;
USE `drone`;
INSERT INTO `drone`.`equipe` ( `Nome`) VALUES ( 'azul');
INSERT INTO `drone`.`equipe` ( `Nome`) VALUES ( 'verde');

COMMIT;

